name: Run Python Script

on:
  push:
    branches:
      - main  # Replace with the branch name you want to trigger the action
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy  # Add dependencies here if required

    - name: Run Script
      run: python scripts/script.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fractal-image
        path: fractal.png  # Path to the image file
